config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/decube83/sqaas-cpp-test:
      branch: main
      repo: https://gitlab.com/decube83/sqaas-cpp-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-indigo-booby.sh
        container: qc.acc_pretty-wheat-camel
  QC.Doc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cinnamon-bat.sh
        container: qc.doc_slaphappy-cyan-rattlesnake
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-chocolate-peccary.sh
        container: qc.doc_dorky-grey-spoonbill
      gitlab.com/decube83/sqaas-cpp-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-olivine-buzzard.sh
        container: qc.doc_paltry-mauve-gopher
  QC.Lic:
    repos:
      gitlab.com/decube83/sqaas-cpp-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-platinum-barnacle.sh
        container: qc.lic_randy-lime-gecko
  QC.Sec:
    repos:
      gitlab.com/decube83/sqaas-cpp-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-apricot-woodlouse.sh
        container: qc.sec_queasy-cerise-markhor
  QC.Sty:
    repos:
      gitlab.com/decube83/sqaas-cpp-test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-gold-wolf.sh
        container: qc.sty_scanty-olivine-hedgehog
      gitlab.com/decube83/sqaas-cpp-test oclint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-seashell-havanese.sh
        container: qc.sty_seedy-maroon-ant
  QC.Uni:
    repos:
      gitlab.com/decube83/sqaas-cpp-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-periwinkle-toucan.sh
        container: qc.uni_baggy-thistle-emu
  QC.Ver:
    repos:
      gitlab.com/decube83/sqaas-cpp-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-mauve-elephant.sh
        container: qc.ver_tasty-sapphire-wrasse
timeout: 5400
