config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/decube83/sqaas-cpp-test:
      branch: main
      repo: https://gitlab.com/decube83/sqaas-cpp-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-sangria-jellyfish.sh
        container: qc.acc_droopy-peach-mayfly
  QC.Doc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-brown-peccary.sh
        container: qc.doc_sunny-cerise-octopus
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-crimson-drever.sh
        container: qc.doc_snappy-dandelion-wolf
      gitlab.com/decube83/sqaas-cpp-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-firebrick-mandrill.sh
        container: qc.doc_shaggy-pear-rottweiler
  QC.Lic:
    repos:
      gitlab.com/decube83/sqaas-cpp-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cardinal-bullfrog.sh
        container: qc.lic_chewy-taupe-caterpillar
  QC.Sty:
    repos:
      gitlab.com/decube83/sqaas-cpp-test oclint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-jade-bee.sh
        container: qc.sty_shabby-copper-bloodhound
  QC.Ver:
    repos:
      gitlab.com/decube83/sqaas-cpp-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-razzmatazz-macaque.sh
        container: qc.ver_lumpy-magnolia-peccary
timeout: 5400
