config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/decube83/sqaas-cpp-test:
      branch: main
      repo: https://gitlab.com/decube83/sqaas-cpp-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-indigo-lizard.sh
        container: qc.acc_nerdy-azure-wildebeest
  QC.Doc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-tan-hyena.sh
        container: qc.doc_thirsty-fuchsia-spider
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-pumpkin-husky.sh
        container: qc.doc_smelly-maroon-cougar
      gitlab.com/decube83/sqaas-cpp-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-magenta-gorilla.sh
        container: qc.doc_sloppy-smalt-barracuda
  QC.Lic:
    repos:
      gitlab.com/decube83/sqaas-cpp-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-orange-discus.sh
        container: qc.lic_queasy-maroon-moose
  QC.Sty:
    repos:
      gitlab.com/decube83/sqaas-cpp-test oclint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-emerald-cockroach.sh
        container: qc.sty_snippy-apricot-duck
  QC.Ver:
    repos:
      gitlab.com/decube83/sqaas-cpp-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-plum-discus.sh
        container: qc.ver_scaly-jade-hamster
timeout: 5400
