config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/decube83/sqaas-cpp-test:
      branch: main
      repo: https://gitlab.com/decube83/sqaas-cpp-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-viridian-rattlesnake.sh
        container: qc.acc_wiggy-linen-moth
  QC.Doc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-wheat-bear.sh
        container: qc.doc_ugly-smalt-boar
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-silver-meerkat.sh
        container: qc.doc_stinky-cerise-zebu
      gitlab.com/decube83/sqaas-cpp-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-wheat-owl.sh
        container: qc.doc_squirrely-asparagus-tapir
  QC.Lic:
    repos:
      gitlab.com/decube83/sqaas-cpp-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-copper-panda.sh
        container: qc.lic_pokey-bronze-skunk
  QC.Sty:
    repos:
      gitlab.com/decube83/sqaas-cpp-test oclint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-russet-gorilla.sh
        container: qc.sty_goopy-orchid-mongoose
  QC.Ver:
    repos:
      gitlab.com/decube83/sqaas-cpp-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-brown-rottweiler.sh
        container: qc.ver_woolly-magenta-forest
timeout: 5400
