config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/decube83/sqaas-cpp-test:
      branch: main
      repo: https://gitlab.com/decube83/sqaas-cpp-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-pear-tetra.sh
        container: qc.acc_pokey-seashell-jellyfish
  QC.Doc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-white-dolphin.sh
        container: qc.doc_lovely-zucchini-dachshund
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-malachite-mau.sh
        container: qc.doc_crappy-orchid-hyena
      gitlab.com/decube83/sqaas-cpp-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-carmine-dragon.sh
        container: qc.doc_tasty-auburn-wasp
  QC.Lic:
    repos:
      gitlab.com/decube83/sqaas-cpp-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-jade-termite.sh
        container: qc.lic_grumpy-asparagus-hippopotamus
  QC.Sty:
    repos:
      gitlab.com/decube83/sqaas-cpp-test oclint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-myrtle-barb.sh
        container: qc.sty_pretty-cardinal-chinook
  QC.Ver:
    repos:
      gitlab.com/decube83/sqaas-cpp-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-carmine-cat.sh
        container: qc.ver_sloppy-chestnut-fowl
timeout: 5400
