config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/decube83/sqaas-cpp-test:
      branch: main
      repo: https://gitlab.com/decube83/sqaas-cpp-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-russet-dane.sh
        container: qc.acc_chummy-taupe-quoll
  QC.Doc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-charcoal-crocodile.sh
        container: qc.doc_cheeky-lilac-quokka
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-fuchsia-tetra.sh
        container: qc.doc_freaky-ochre-zebra
      gitlab.com/decube83/sqaas-cpp-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-amber-bison.sh
        container: qc.doc_nippy-russet-fossa
  QC.Lic:
    repos:
      gitlab.com/decube83/sqaas-cpp-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-scarlet-rhinoceros.sh
        container: qc.lic_slaphappy-burgundy-bongo
  QC.Sty:
    repos:
      gitlab.com/decube83/sqaas-cpp-test oclint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-ivory-kiwi.sh
        container: qc.sty_silly-ecru-avocet
  QC.Ver:
    repos:
      gitlab.com/decube83/sqaas-cpp-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-maroon-slug.sh
        container: qc.ver_homey-black-cougar
timeout: 5400
