config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/decube83/sqaas-cpp-test:
      branch: main
      repo: https://gitlab.com/decube83/sqaas-cpp-test
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ultramarine-indri.sh
        container: qc.acc_slaphappy-orchid-beetle
  QC.Doc:
    repos:
      gitlab.com/decube83/sqaas-cpp-test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-crimson-affenpinscher.sh
        container: qc.doc_muzzy-rose-magpie
      gitlab.com/decube83/sqaas-cpp-test git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-sapphire-donkey.sh
        container: qc.doc_thirsty-dandelion-uakari
      gitlab.com/decube83/sqaas-cpp-test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-chartreuse-snake.sh
        container: qc.doc_sloppy-chartreuse-tarantula
  QC.Lic:
    repos:
      gitlab.com/decube83/sqaas-cpp-test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-chartreuse-booby.sh
        container: qc.lic_scanty-mustard-maltese
  QC.Sec:
    repos:
      gitlab.com/decube83/sqaas-cpp-test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-puce-zebu.sh
        container: qc.sec_hasty-smalt-seal
  QC.Sty:
    repos:
      gitlab.com/decube83/sqaas-cpp-test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-amethyst-scorpion.sh
        container: qc.sty_dorky-mauve-moorhen
      gitlab.com/decube83/sqaas-cpp-test oclint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-persimmon-tamarin.sh
        container: qc.sty_homey-bistre-akbash
  QC.Uni:
    repos:
      gitlab.com/decube83/sqaas-cpp-test pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-red-paradise.sh
        container: qc.uni_gloppy-bistre-hedgehog
  QC.Ver:
    repos:
      gitlab.com/decube83/sqaas-cpp-test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-indigo-dollar.sh
        container: qc.ver_woolly-wisteria-ibis
timeout: 5400
